name: Clojure simple-server docker build

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server-docker-build.yml'
      - 'server/clojure/simple-server/**'
      - '!server/clojure/simple-server/project.clj'
    branches:
      - main

env:
  BASE_IMAGE: senyorjou/api-wars-clojure-simple-server-base
  APP_IMAGE: senyorjou/api-wars-clojure-simple-server
  TEST_IMAGE: senyorjou/api-wars-clojure-simple-server:test

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and export to Docker
      uses: docker/build-push-action@v5
      with:
        context: server/clojure/simple-server
        load: true
        tags: ${{ env.TEST_TAG }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test
        run: |
          docker run --rm ${{ env.TEST_IMAGE }} 'lein test'

    - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: server/clojure/simple-server
          push: true
          tags: ${{ env.APP_IMAGE }}
