name: Clojure simple-server-base

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server-base.yml'
      - './server/clojure/simple-server/project.clj'
    branches:
      - main

  pull_request:
    paths:
      - '.github/workflows/clojure-simple-server-base.yml'
      - './server/clojure/simple-server/project.clj'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - uses: actions/checkout@v3

    - name: Cache lein project dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: m2-clojure-simple-server-base-${{ hashFiles('./server/clojure/simple-server/project.clj') }}

    - name: Install dependencies
      run: lein deps

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker && push image
      run: |
        docker buildx build --push \
        -t senyorjou/api-wars-clojure-simple-server-base \
        -f ./Dockerfile.base .
