name: Clojure simple-server

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server.yml'
      - './server/clojure/simple-server/**'
    branches:
      - main

  pull_request:
    paths:
      - '.github/workflows/clojure-simple-server.yml'
      - './server/clojure/simple-server/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - uses: actions/checkout@v3

    - name: Cache lein project dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-clojure-simple-server-${{ hashFiles('./project.clj') }}
        restore-keys: |
          ${{ runner.os }}-clojure-simple-server

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test
