name: Clojure simple-server docker build

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server-docker-build.yml'
      - 'server/clojure/simple-server/**'
      - '!server/clojure/simple-server/project.clj'
    branches:
      - main

env:
  BASE_IMAGE: senyorjou/api-wars-clojure-simple-server-base
  APP_IMAGE: senyorjou/api-wars-clojure-simple-server

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: $APP_IMAGE:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
