name: Clojure simple-server-base-self

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server-self.yml'
      - 'server/clojure/simple-server/project.clj'

    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker pull (for cache)
      run: |
        docker pull senyorjou/api-wars-clojure-simple-server-base || true

    - name: Build docker && push image
      run: |
        docker buildx build --cache-from senyorjou/api-wars-clojure-simple-server-base\
        -t senyorjou/api-wars-clojure-simple-server-base \
        -f ./Dockerfile.base .

    - name: Docker push
      run: |
        docker push senyorjou/api-wars-clojure-simple-server-base
