name: Clojure simple-server

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server.yml'
      - './server/clojure/simple-server/**'
    branches:
      - main

  pull_request:
    paths:
      - '.github/workflows/clojure-simple-server.yml'
      - './server/clojure/simple-server/**'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - uses: actions/checkout@v3

    - name: Cache lein project dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: m2-clojure-simple-server-${{ hashFiles('./project.clj') }}

    - name: Install dependencies
      run: lein deps

    - name: Run tests
      run: lein test

    - name: Build docker image
      run: docker buildx build -t senyorjou/api-wars-clojure-simple-server .

    - name: Push docker image
      run: docker push senyorjou/api-wars-clojure-simple-server .
