name: Clojure simple-server

on:
  push:
    paths:
      - .github/workflows/clojure-simple-server.yml
      - ./server/clojure/simple-server/**
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - uses: actions/checkout@v3
    - name: Install dependencies
      run: lein deps
    - name: Run tests
      run: lein test
