name: Clojure simple-server-base-self

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server-self.yml'
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build docker && push image
      run: |
        docker buildx build \
        -t senyorjou/api-wars-clojure-simple-server-base \
        -f ./Dockerfile.base .

    - name: Run tests
      run: |
        docker run --rm \
        senyorjou/api-wars-clojure-simple-server-base \
        lein test

    - name: Docker push
      run: |
        docker push senyorjou/api-wars-clojure-simple-server-base
