name: Clojure simple-server

on:
  push:
    paths:
      - '.github/workflows/clojure-simple-server.yml'
      - 'server/clojure/simple-server/**'
      - '!server/clojure/simple-server/project.clj'
    branches:
      - main

  pull_request:
    paths:
      - '.github/workflows/clojure-simple-server.yml'
      - './server/clojure/simple-server/**'
      - '!server/clojure/simple-server/project.clj'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server/clojure/simple-server
    steps:
    - uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker pull (for cache)
      run: |
        docker pull senyorjou/api-wars-clojure-simple-server-base || true

    - name: Run tests, build docker && push image
      run: |
        docker buildx build \
        --cache-from senyorjou/api-wars-clojure-simple-server-base \
        --push \
        -t senyorjou/api-wars-clojure-simple-server \
        -f ./Dockerfile .
